import type { Metadata } from "next";
import "./globals.css";
import { Karla } from "next/font/google";

// components
import Navbar from "./components/Navbar";

const karla = Karla({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${karla.className} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
